### ISSUE TITLE
creds.json file missing

### ISSUE THREAD

**Issue by jdelforno** [PaloAltoNetworks/terraform-provider-prismacloud-waas#5]
## Documentation link

https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud-waas/latest/docs#config_file

## Describe the problem

[config_file](https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud-waas/latest/docs#config_file) (String) Configuration file in JSON format. See examples/creds.json

There is no creds.json file

## Suggested fix

Commit the creds.json example

**Comment by pan0ptic0n** [comment]
This was an artifact left over from the scaffolding. This file has been removed and creds via file is not currently supported.
